language: python
python:
    - 2.7

env:
    - PLATFORMIO_CI_SRC=src/main.cpp
    - PLATFORMIO_CI_SRC=lib/Parser/src/Parser.cpp
install:
    - pip install platformio

script:
    - platformio ci --board=teensy35 --board=teensy36
