language: python
python:
    - 2.7

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src
install:
    - pip install platformio

script:
    - platformio ci --board=teensy35 --board=teensy36
