dist: trusty
sudo: required
language: python
python:
    - 2.7

cache:
    directories:
        - "~/.platformio"

# Configuration variables.
env:
  global:
    - ROS_DISTRO=indigo
    - ROS_CI_DESKTOP="`lsb_release -cs`"  # e.g. [precise|trusty|...]
    - CI_SRC_PATH=$(pwd)  
  matrix:
    - PLATFORMIO_CI_SRC=$CI_SRC_PATH/kitt_teensy_ros_node

before_install:
    # Get roskeys
    - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
    - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
    - sudo apt-get -qq update

install:
    # Install minimum amount of ROS to get things working for rosserial.
    - sudo apt-get install -y ros-$ROS_DISTRO-catkin
    - sudo apt-get install -y python-rosdep
    - sudo apt-get install -y ros-$ROS_DISTRO-rosbash
    - sudo apt-get install -y ros-$ROS_DISTRO-roscpp
    - sudo apt-get install -y ros-$ROS_DISTRO-roslib
    - sudo apt-get install -y ros-$ROS_DISTRO-rospy
    - sudo apt-get install -y ros-$ROS_DISTRO-common-msgs
    - sudo apt-get install -y ros-$ROS_DISTRO-topic-tools
    - sudo apt-get install -y ros-$ROS_DISTRO-tf
    - pip install -U rospkg
    - pip install -U catkin_pkg
    - pip install -U empy
    - source /opt/ros/$ROS_DISTRO/setup.bash
    # Prepare rosdep to install dependencies.
    - sudo rosdep init
    - rosdep update
    # Install platformio
    - pip install platformio
    ### Get platformio libs.
    # Install Timer.h library for easy ISRs.
    # http://platformio.org/lib/show/75/Timer
    # Pull in custom IMU libraries that use the i2c_t3.h instead of Timer.h
    - platformio lib -g install 75 https://github.com/Teensy-Compatible-Libraries/lsm6-arduino.git https://github.com/Teensy-Compatible-Libraries/lis3mdl-arduino.git

before_script:
    ### Build rosserial
    # Initialize catkin workspace for custom rosserial build.
    - mkdir -p ~/catkin_ws/src
    - cd ~/catkin_ws/src
    - catkin_init_workspace
    # Pull in custom rosserial because PR https://github.com/ros-drivers/rosserial/pull/270
    # hasn't made it to the debs yet. When it does, this should be removed.
    - git clone https://github.com/ros-drivers/rosserial.git --branch $ROS_DISTRO-devel
    # Include custom kitt_msgs
    - git clone https://github.com/kittcar/kitt_msgs.git
    - cd ~/catkin_ws
    - catkin_make
    - source ~/catkin_ws/devel/setup.bash
    # Make sketchbook/libraries folder.
    - mkdir -p $CI_SRC_PATH/sketchbook/libraries
    - export CI_LIB_PATH=$CI_SRC_PATH/sketchbook/libraries
    # Make rosserial_arduino in the sketchbook/libraries folder
    - rosrun rosserial_arduino make_libraries.py $CI_LIB_PATH
    
script:
    # Build code
    - platformio ci --lib="$CI_LIB_PATH/ros_lib" --board=teensy35 --board=teensy36

deploy:
    provider: s3
    access_key_id: AKIAIVN2KOJ2CVJA7SPA
    secret_access_key:
        secure: b5iXLbT8Lbwks2CEoQeduTcVAtMKB2G4UOVzCnHn6xKA0tSkJg8ePSbwqx+J4kM3ChCM+1Z++qRsl5+jYI370e78GTogivA17E4eThvUcgaDqg/QgVTOzRG0E35I0OQnrcgE4zF0CFmTIjl+rvpCQz6w4jZ6+IUjK7ZmjEVzQ2DxCwSpCw5xgVHfkvWbYbr63JAdfFqkcYDx+YXIjhHJbJpREcgmYkLIFyNaTwkdSUP8HwD3cOniXgasV+H/2DJlzEvueRO1VntjjP/ourdrf5YA3OZBQYqLWCNTnTDviLwyOh3VyL20GlBHCy3LOco73V2suJd1EQYnQFUS7a9qGgM3FgN8AA4OGXFWcIzqmEywoHRb1MBbatJHxuzQNSwnZuGymWKTUxbl8HNtbyu+wu/7D/bxKz84vzcHtpqu3Ezf0VPGZ5ZCV05ZnmAH8Yn90yop2Gw/g+IRxMEnkXJUwRgrgS12WXKkIgv5HofTD4Z78EiZEtLToSlhkT/eNAzPmyElZ6E3mFpx1TUc2T+uuVk3oPmcyDiMkH76rm6Ggs84GrQoc7HB/o+GLNc1GtaBNs76KCHUVhrz1fOOPo7xGaz5SMJ6pA9eHZavo5lE9zjFYkYK01v12wKCz08iXzET/bLTSAdYSqkBV7hEeQimdEFntA7ssmYRYlFkTJz3Fwk=
    bucket: api.kittcar.com
    acl: public_read
    on:
        repo: kittcar/kitt_platform
    skip_cleanup: true
    region: us-west-1
    local_dir: docs
    upload_dir: kitt_platform

