dist: trusty
sudo: required
language: python
python:
- 2.7
cache:
  directories:
  - "~/.platformio"
env:
  global:
  - ROS_DISTRO=indigo
  - ROS_CI_DESKTOP="`lsb_release -cs`"
  - CI_SRC_PATH=$(pwd)
before_install:
- sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\"
  > /etc/apt/sources.list.d/ros-latest.list"
- wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
- sudo apt-get -qq update
install:
- sudo apt-get install -y ros-$ROS_DISTRO-catkin
- sudo apt-get install -y python-rosdep
- sudo apt-get install -y ros-$ROS_DISTRO-rosbash
- sudo apt-get install -y ros-$ROS_DISTRO-roscpp
- sudo apt-get install -y ros-$ROS_DISTRO-roslib
- sudo apt-get install -y ros-$ROS_DISTRO-rospy
- sudo apt-get install -y ros-$ROS_DISTRO-common-msgs
- sudo apt-get install -y ros-$ROS_DISTRO-topic-tools
- sudo apt-get install -y ros-$ROS_DISTRO-tf
- sudo apt-get install -y ros-$ROS_DISTRO-ackermann-msgs
- pip install -U rospkg
- pip install -U catkin_pkg
- pip install -U empy
- source /opt/ros/$ROS_DISTRO/setup.bash
- sudo rosdep init
- rosdep update
- pip install platformio
before_script:
- mkdir -p ~/catkin_ws/src
- cd ~/catkin_ws/src
- catkin_init_workspace
- git clone https://github.com/ros-drivers/rosserial.git --branch $ROS_DISTRO-devel
- git clone https://github.com/kittcar/kitt_msgs.git
- cd ~/catkin_ws
- catkin_make
- source ~/catkin_ws/devel/setup.bash
- mkdir -p sketchbook/libraries
- export ROSSERIAL_LIB_PATH=$(cd sketchbook/libraries; pwd)
- rosrun rosserial_arduino make_libraries.py $ROSSERIAL_LIB_PATH
- cd src
- git clone https://github.com/kittcar/Catch2.git
- export CATCH2_SINGLE_INCLUDE_DIR=$(cd Catch2/single_include; pwd)
- ln -s $CI_SRC_PATH .
script:
- cd ~/catkin_ws/src/kitt_platform/balor
- platformio run
- cd lib/balor
- mkdir build
- cd build
- cmake ..
- make
- make test
after_failure:
- make check
before_deploy:
- sudo apt-get install -y doxygen
- cd $CI_SRC_PATH
- doxygen
deploy:
  provider: s3
  access_key_id: AKIAJCAG4GDO3A32L3KA
  secret_access_key:
    secure: TiRn/uD/x/Px/q8rlkN54cud9YzG9dwjBc3ZP47KEQkWcZJWEmAUYzi7WVusqExAVK7A7TOsN0SItDKT/0GD0zJMrqgowAOSACPL8xPmUvKHDLqw6p14J/79O76+NVP3Q5X/InYMPtZwwu/6LvKJ3PVVMlwsKUWWhjgUvjpM6hExSMKPm59FBJ4S/M01rZ/AqFYCj6TrIO6nlMS4tgODmMpdJ5bmQnevJb19ugfxAi6MPoDKwok9evdKgkpviWvhLhYBvG7B+7OjzbMC8upYjkhtv91WKlCEhAkf5mAXbvZ4uDLtAuVqzP0XDM53ZhOirtrgd2brY5KBLN2ecn8nXV/A/CYp6V/7QUCI15uQaEf99GQOxj2IQUnpvfhPss4/+67fyuJqfOdXJPHWPzCzs/Rg1kyypd3ydos3qzIbKBjb+/DSbnMQuVYsI35Zg+vSX/ARU6DthfEXD3r77p3PTka67NnF5KlhTCM4MWT8e+l+3jfqTURMnKIHvuKm4AnC05//fn3IU3TaIG01qumppxVNq6Tfe98tJZQOOs8lsEAGYfgGvh4+DLA21uhUvBvK+EyJqufT8fU7e/aqnWnKZ4c82ICVDbOquTsV0H/GdXF2m3PoP/8a9P34YSPF/OBDMuXBfafuhF//8SZEbEfh3dazzz7g0WIiNE2AJOZE00M=
  bucket: api.kittcar.com
  local-dir: '$CI_SRC_PATH/docs'
  upload-dir: kitt_platform
  skip_cleanup: true
  region: us-west-1
  acl: public_read
  on:
    repo: kittcar/kitt_platform
